# version: '3.9'
# services:
#   db:
#     image: postgres:latest
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=Qwert113
#     ports:
#       - '5432:5432'
#     volumes:
#       - db:/var/lib/postgresql/data

version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Qwert113
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=avilovd.a@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
  pgadmin:
